#!/usr/bin/env python3
"""Render every generated file in this repo from two inputs:

  mcp.config.json       URLs, names, contacts (edit this)
  catalog/catalog.json  tools/prompts/resources, generated from the server code
                        (`make sync` in the private gupshup-mcp-server repo)

Outputs (do not edit by hand, they are overwritten):
  README.md sections between <!-- BEGIN:x --> / <!-- END:x --> markers
  docs/reference/{analytics,templates,campaigns}.md, docs/prompts.md
  docs/clients/*.md, docs/self-serve.md
  server.json, .claude-plugin/marketplace.json,
  plugins/gupshup-mcp/.claude-plugin/plugin.json, plugins/gupshup-mcp/.mcp.json,
  plugins/gupshup-mcp/.cursor-plugin/plugin.json, plugins/gupshup-mcp/mcp.json, .cursor-plugin/marketplace.json

Stdlib only.  Usage: python3 scripts/render_docs.py [--check]
--check exits 1 if any output would change (CI drift guard).
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CFG = json.loads((ROOT / "mcp.config.json").read_text())
CATALOG = json.loads((ROOT / "catalog" / "catalog.json").read_text())

URL = CFG["mcp_url_legacy"] if CFG["use_legacy_as_primary"] else CFG["mcp_url"]
NAME = CFG["server_name"]
RISK = {"read": "Read-only", "write": "Writes", "sends": "**Sends messages**", "destructive": "**Deletes data**"}
APP_BY_KEY = {a["key"]: a for a in CATALOG["apps"]}
GENERATED = "<!-- Generated by scripts/render_docs.py from catalog/catalog.json. Do not edit by hand. -->\n"

outputs: dict[Path, str] = {}


def emit(rel: str, content: str) -> None:
    outputs[ROOT / rel] = content if content.endswith("\n") else content + "\n"


def emit_json(rel: str, data: object) -> None:
    emit(rel, json.dumps(data, indent=2, ensure_ascii=False))


def md_escape(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


# ---------- install links ----------
# GitHub strips cursor:// and vscode: links from rendered Markdown, so buttons use
# the vendors' https redirect pages, which hand off to the installed app.
CURSOR_BADGE = "https://cursor.com/deeplink/mcp-install-dark.svg"
VSCODE_BADGE = "https://img.shields.io/badge/VS_Code-Install_Gupshup-0098FF?style=for-the-badge"
CLAUDE_BADGE = "https://img.shields.io/badge/Claude-Add_Gupshup-D97757?style=for-the-badge&logo=claude&logoColor=white"
VSCODE_INS_BADGE = "https://img.shields.io/badge/VS_Code_Insiders-Install_Gupshup-24bfa5?style=for-the-badge"


def cursor_config(url: str, headers: dict | None = None) -> str:
    cfg = {"url": url, **({"headers": headers} if headers else {})}
    return urllib.parse.quote(base64.b64encode(json.dumps(cfg, separators=(",", ":")).encode()).decode(), safe="")


def cursor_link(name: str = NAME, url: str = URL, headers: dict | None = None) -> str:
    """Native deeplink (for the website / copy-paste)."""
    return f"cursor://anysphere.cursor-deeplink/mcp/install?name={name}&config={cursor_config(url, headers)}"


def cursor_https(name: str = NAME, url: str = URL, headers: dict | None = None) -> str:
    """https page on cursor.com that opens Cursor's install dialog: works from GitHub."""
    return f"https://cursor.com/install-mcp?name={name}&config={cursor_config(url, headers)}"


def vscode_link(insiders: bool = False) -> str:
    cfg = urllib.parse.quote(json.dumps({"type": "http", "url": URL}, separators=(",", ":")), safe="")
    host = "insiders.vscode.dev" if insiders else "vscode.dev"
    return f"https://{host}/redirect/mcp/install?name={NAME}&config={cfg}" + ("&quality=insiders" if insiders else "")


def claude_link(admin: bool = False) -> str:
    """Official prefill link: opens Claude's Add-custom-connector dialog with name + URL filled in."""
    base = "https://claude.ai/admin-settings/connectors" if admin else "https://claude.ai/customize/connectors"
    return (f"{base}?modal=add-custom-connector&connectorName=Gupshup"
            f"&connectorUrl={urllib.parse.quote(URL, safe='')}")


def install_buttons() -> str:
    return (f"[![Add to Claude]({CLAUDE_BADGE})]({claude_link()}) "
            f"[![Add to Cursor]({CURSOR_BADGE})]({cursor_https()}) "
            f"[![Install in VS Code]({VSCODE_BADGE})]({vscode_link()}) "
            f"[![Install in VS Code Insiders]({VSCODE_INS_BADGE})]({vscode_link(insiders=True)})")


# ---------- reference docs ----------
def schema_type(p: dict) -> str:
    if "enum" in p:
        return " \\| ".join(f"`{json.dumps(v)}`" for v in p["enum"])
    if "anyOf" in p:
        parts = [schema_type(x) for x in p["anyOf"] if x.get("type") != "null"]
        return " \\| ".join(parts) or "any"
    if p.get("type") == "array":
        return f"{schema_type(p.get('items', {}))}[]"
    if "$ref" in p:
        return p["$ref"].rsplit("/", 1)[-1]
    return f"`{p.get('type', 'object')}`"


def params_table(schema: dict | None) -> str:
    props = (schema or {}).get("properties") or {}
    if not props:
        return "_No parameters._\n"
    required = set((schema or {}).get("required") or [])
    with_desc = any((p.get("description") or "").strip() for p in props.values())
    head = "| Parameter | Type |" + (" Description |" if with_desc else "") + "\n"
    head += "|---|---|" + ("---|" if with_desc else "") + "\n"
    rows = []
    for name, p in props.items():
        req = " **(required)**" if name in required else ""
        row = f"| `{name}`{req} | {schema_type(p)} |"
        if with_desc:
            row += f" {md_escape(p.get('description', ''))} |"
        rows.append(row)
    return head + "\n".join(rows) + "\n"


def render_reference() -> None:
    for app in CATALOG["apps"]:
        tools = [t for t in CATALOG["tools"] if t["app"] == app["key"]]
        callable_ = [t for t in tools if not t["app_only"]]
        panel = [t for t in tools if t["app_only"]]
        out = [GENERATED, f"# {app['label']} tools\n",
               f"{app['summary']}\n",
               f"**OAuth scope:** {', '.join(f'`{s}`' for s in app['scopes'])} · "
               f"**Tools:** {len(callable_)} callable" + (f" + {len(panel)} review-panel actions" if panel else "") +
               f" · **Approx. context cost:** ~{round(app['approx_tool_tokens'] / 100) / 10}k tokens\n",
               "| Tool | What it does | Action |\n|---|---|---|"]
        out += [f"| [`{t['name']}`](#{t['name']}) | {md_escape(t['summary'])} | {RISK[t['risk']]} |" for t in callable_]
        out.append("")
        for t in callable_:
            out += [f"## `{t['name']}`\n", f"{t['summary']}\n"]
            meta = [f"**Action:** {RISK[t['risk']]}"]
            if t["channels"]:
                meta.append("**Channels:** " + ", ".join(t["channels"]))
            if t["ui_resource"]:
                meta.append(f"**Opens panel:** `{t['ui_resource']}`")
            out += [" · ".join(meta) + "\n", params_table(t["input_schema"])]
            out += ["<details><summary>Model-facing description</summary>\n", f"{t['description']}\n", "</details>\n"]
        if panel:
            out += ["## Review-panel actions\n",
                    "These tools are called by the interactive review panel (MCP Apps) when you click in it. "
                    "They are not offered to the model, and clients that don't render panels never call them.\n",
                    "| Tool | Panel | Purpose |\n|---|---|---|"]
            out += [f"| `{t['name']}` | `{t['ui_resource']}` | {md_escape(t['summary'])} |" for t in panel]
            out.append("")
        emit(f"docs/reference/{app['key']}.md", "\n".join(out))


def render_prompts() -> None:
    out = [GENERATED, "# Prompts\n",
           "Prompts are ready-made starting points. In clients that support MCP prompts they appear as slash commands "
           "(for example `/mcp__gupshup__draft-message-template` in Claude Code); elsewhere, paste the example as your message.\n"]
    for app in CATALOG["apps"]:
        prompts = [p for p in CATALOG["prompts"] if p["app"] == app["key"]]
        out += [f"## {app['label']}\n", "| Prompt | What it does | Try asking |\n|---|---|---|"]
        for p in prompts:
            desc = p.get("friendly_description") or p["description"]
            example = f"“{md_escape(p['example'])}”" if p.get("example") else ""
            out.append(f"| `/{p['name']}` | {md_escape(desc)} | {example} |")
        out.append("")
    out += ["## Interactive review panels\n",
            "Panels are MCP Apps (`ui://` resources) that render inside clients that support them. "
            "Clients without MCP Apps support get the same information as text, and launches still require confirmation.\n",
            "| Panel | Purpose |\n|---|---|"]
    out += [f"| `{r['uri']}` | {md_escape(r['description'])} |" for r in CATALOG["resources"]]
    emit("docs/prompts.md", "\n".join(out))


# ---------- client guides ----------
def render_clients() -> None:
    legacy_note = (
        f"\n> Already using `{CFG['mcp_url_legacy']}`? It stays supported permanently; no change needed.\n"
        if not CFG["use_legacy_as_primary"] else ""
    )
    signin = ("When prompted, sign in with your **Gupshup Enterprise account ID and password** for each channel "
              "(WhatsApp, SMS, RCS) you want to use, then choose which apps (Analytics, Templates, Campaigns) to allow.")
    guides = {
        "claude": ("Claude (web, desktop & mobile)", f"""
**One click:**

[![Add to Claude]({CLAUDE_BADGE})]({claude_link()})

1. The button opens Claude's **Add custom connector** dialog with the name and URL filled in. Review it and click **Add**.
2. Click **Connect**. {signin}
3. In a chat, enable Gupshup from **+ → Connectors**.

The connector syncs to Claude Desktop and mobile, and to Claude Code when you're signed in with the same claude.ai account.

**Team & Enterprise plans:** an Owner adds it once for the organization with the [admin install link]({claude_link(admin=True)}). Each member then connects their own Gupshup account.

**Manual setup:** **Customize → Connectors → Add custom connector**, name `Gupshup`, URL:
```
{URL}
```
"""),
        "claude-code": ("Claude Code", f"""
```bash
claude mcp add --transport http --scope user {NAME} {URL}
```
Then run `/mcp` inside Claude Code, select **{NAME}** and choose **Authenticate**. {signin}

**Already added Gupshup in claude.ai?** With the same account signed in to Claude Code, it's already available: run `/mcp` to check.

**Share with your team:** commit this as `.mcp.json` at your project root. Claude Code asks each teammate to approve it once:
```json
{json.dumps({"mcpServers": {NAME: {"type": "http", "url": URL}}}, indent=2)}
```

**Or install the plugin** (same server, plus updates through the marketplace):
```
/plugin marketplace add GupshupSuperAgent/mcp
/plugin install gupshup-mcp@gupshup
```
"""),
        "cursor": ("Cursor", f"""
**One click** (Cursor must be installed):

[![Add to Cursor]({CURSOR_BADGE})]({cursor_https()})

The button opens Cursor's *Install MCP server* dialog; click **Install**. If your browser doesn't hand off to Cursor, paste this link into the address bar:
```
{cursor_link()}
```

Or add to `~/.cursor/mcp.json` (all projects) or `.cursor/mcp.json` (one project):
```json
{json.dumps({"mcpServers": {NAME: {"url": URL}}}, indent=2)}
```
Cursor opens your browser to sign in. {signin}
"""),
        "vscode": ("VS Code (GitHub Copilot)", f"""
**One click** (VS Code must be installed):

[![Install in VS Code]({VSCODE_BADGE})]({vscode_link()}) [![Install in VS Code Insiders]({VSCODE_INS_BADGE})]({vscode_link(insiders=True)})

The button opens VS Code's MCP install page; click **Install**.

Or from a terminal:
```bash
code --add-mcp '{json.dumps({"name": NAME, "type": "http", "url": URL}, separators=(",", ":"))}'
```
Or add to `.vscode/mcp.json`:
```json
{json.dumps({"servers": {NAME: {"type": "http", "url": URL}}}, indent=2)}
```
Start the server from the MCP view (or the CodeLens in `mcp.json`); VS Code prompts you to sign in. {signin}
"""),
        "chatgpt": ("ChatGPT", f"""
1. In ChatGPT settings, turn on **Developer mode** (workspace admins may need to allow it first).
2. Add a new app/connector: name `Gupshup`, server URL `{URL}`, authentication **OAuth**.
3. {signin}
4. In a chat, enable Gupshup from the tools menu.

Menu labels vary by plan and are changing as OpenAI rolls out apps; look for Developer mode under Settings.
"""),
        "codex": ("OpenAI Codex CLI", f"""
```bash
codex mcp add {NAME} --url {URL}
codex mcp login {NAME}
```
Or in `~/.codex/config.toml`:
```toml
[mcp_servers.{NAME}]
url = "{URL}"
```
"""),
        "windsurf": ("Windsurf / Devin Desktop", f"""
Add to `~/.codeium/windsurf/mcp_config.json` (Windsurf) or `~/.config/devin/mcp_config.json` (Devin Desktop):
```json
{json.dumps({"mcpServers": {NAME: {"serverUrl": URL}}}, indent=2)}
```
"""),
        "other": ("Other clients & SDKs", f"""
Any MCP client that supports **remote servers over Streamable HTTP** with **OAuth 2.1** (authorization code + PKCE, dynamic client registration) works:
```json
{json.dumps({"mcpServers": {NAME: {"type": "http", "url": URL}}}, indent=2)}
```
Clients that only support local (stdio) servers can use the [`mcp-remote`](https://www.npmjs.com/package/mcp-remote) bridge:
```json
{json.dumps({"mcpServers": {NAME: {"command": "npx", "args": ["-y", "mcp-remote", URL]}}}, indent=2)}
```
"""),
    }
    index = [GENERATED, "# Connect a client\n", f"Server URL: `{URL}`{legacy_note}\n", "| Client | Guide |\n|---|---|"]
    for key, (title, body) in guides.items():
        emit(f"docs/clients/{key}.md", f"{GENERATED}# {title}\n{legacy_note}{body}\n"
             "No Gupshup Enterprise account yet? Email "
             f"[{CFG['sales_email']}](mailto:{CFG['sales_email']}).\n\n"
             "Something not working? See [Troubleshooting](../troubleshooting.md).\n")
        index.append(f"| {title} | [{key}.md]({key}.md) |")
    emit("docs/clients/README.md", "\n".join(index))


# ---------- self-serve (API-key) server ----------
SS = CFG["self_serve"]


def render_self_serve() -> None:
    url, name, hdr, env = SS["mcp_url"], SS["server_name"], SS["auth_header"], SS["env_var"]
    vscode = {
        "inputs": [{"type": "promptString", "id": "gupshup-api-key", "description": "Gupshup API key", "password": True}],
        "servers": {name: {"type": "http", "url": url, "headers": {hdr: "${input:gupshup-api-key}"}}},
    }
    body = f"""{GENERATED}# Self-serve: Gupshup API MCP

For developers and businesses on the **Gupshup messaging API** ([reference]({SS['api_docs_url']})). This MCP server is hosted on the Gupshup docs portal. Connect it to your AI client and your agent can work with the messaging API: WhatsApp, SMS, RCS and more.

> Enterprise customers (analytics, templates and campaigns through OAuth sign-in) use the [Enterprise server](clients/README.md) instead. You can connect both.

| | |
|---|---|
| Server URL | `{url}` |
| Transport | Streamable HTTP |
| Auth | Your Gupshup **API key** in the `{hdr}` header |
| API reference | {SS['api_docs_url']} |

**Get your API key** from your Gupshup account dashboard. Keep it out of shared or committed files: the snippets below read it from the `{env}` environment variable, or prompt for it.

```bash
export {env}="<your Gupshup API key>"
```

## Claude Code
```bash
claude mcp add --transport http --scope user {name} {url} --header "{hdr}: ${env}"
```

## Cursor
[![Add to Cursor]({CURSOR_BADGE})]({cursor_https(name, url, {hdr: "${env:" + env + "}"})})

The button adds the server with the key read from `{env}`: set that variable, then restart Cursor. Or add it to `~/.cursor/mcp.json` yourself:
```json
{json.dumps({"mcpServers": {name: {"url": url, "headers": {hdr: "${env:" + env + "}"}}}}, indent=2)}
```

## VS Code
`.vscode/mcp.json`. VS Code prompts for the key once and stores it securely:
```json
{json.dumps(vscode, indent=2)}
```

## OpenAI Codex CLI
`~/.codex/config.toml`:
```toml
[mcp_servers.{name}]
url = "{url}"
env_http_headers = {{ "{hdr}" = "{env}" }}
```

## Windsurf / Devin Desktop
```json
{json.dumps({"mcpServers": {name: {"serverUrl": url, "headers": {hdr: "${env:" + env + "}"}}}}, indent=2)}
```

## Claude Desktop and other stdio-only clients
Use the [`mcp-remote`](https://www.npmjs.com/package/mcp-remote) bridge to add the header:
```json
{json.dumps({"mcpServers": {name: {"command": "npx", "args": ["-y", "mcp-remote", url, "--header", f"{hdr}:${{{env}}}"], "env": {env: "<your Gupshup API key>"}}}}, indent=2)}
```

## Claude.ai and ChatGPT (web)
Their custom connectors authenticate with OAuth and don't let you set an API-key header, so this server can't be added there yet. Use one of the clients above.

## Security
- Your API key can send messages and incur charges, so treat it like a password. Don't paste it into chats, issues or committed config files.
- Rotate the key from your Gupshup dashboard if it's exposed.
- Keep your client's tool-approval prompts on for anything that sends messages.

No account yet? Sign up at [gupshup.ai](https://www.gupshup.ai), or talk to [sales]({"mailto:" + CFG['sales_email']}).
"""
    emit("docs/self-serve.md", body)


# ---------- manifests ----------
def render_manifests() -> None:
    description = ("Gupshup messaging for AI agents: analytics, templates and campaigns across "
                   "WhatsApp, SMS and RCS.")
    emit_json("server.json", {
        "$schema": "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
        "name": CFG["registry_name"],
        "title": "Gupshup",
        "description": description[:100],
        "version": CFG["version"],
        "websiteUrl": CFG["website_url"],
        "repository": {"url": CFG["repo_url"], "source": "github"},
        "remotes": [{"type": "streamable-http", "url": URL}],
    })
    emit_json(".claude-plugin/marketplace.json", {
        "name": "gupshup",
        "description": "Official Gupshup plugins for Claude Code",
        "owner": {"name": "Gupshup", "url": CFG["website_url"]},
        "plugins": [{
            "name": "gupshup-mcp",
            "source": "./plugins/gupshup-mcp",
            "description": description,
        }],
    })
    emit_json("plugins/gupshup-mcp/.claude-plugin/plugin.json", {
        "name": "gupshup-mcp",
        "version": CFG["version"],
        "description": description,
        "author": {"name": "Gupshup", "url": CFG["website_url"]},
        "homepage": CFG["website_url"],
        "repository": CFG["repo_url"],
        "license": "MIT",
        "keywords": ["gupshup", "whatsapp", "sms", "rcs", "messaging", "cpaas", "campaigns"],
    })
    emit_json("plugins/gupshup-mcp/.mcp.json", {"mcpServers": {NAME: {"type": "http", "url": URL}}})

    # Cursor Marketplace: same plugin folder (Cursor reads mcp.json, Claude Code reads .mcp.json).
    cursor_desc = ("Run WhatsApp, SMS and RCS from Cursor: Gupshup analytics, template drafting and approval, "
                   "and A/B, multilingual and scheduled campaigns, with a human review step before anything is sent.")
    keywords = ["gupshup", "whatsapp", "whatsapp-business-api", "sms", "rcs", "messaging", "cpaas", "campaigns",
                "templates", "marketing", "analytics", "mcp"]
    emit_json("plugins/gupshup-mcp/mcp.json", {"mcpServers": {NAME: {"type": "http", "url": URL}}})
    emit_json("plugins/gupshup-mcp/.cursor-plugin/plugin.json", {
        "name": "gupshup",
        "displayName": "Gupshup",
        "version": CFG["version"],
        "description": cursor_desc,
        "author": {"name": "Gupshup", "url": "https://www.gupshup.ai"},
        "homepage": CFG["website_url"],
        "repository": CFG["repo_url"],
        "license": "MIT",
        "keywords": keywords,
        "logo": "assets/logo.svg",
        "skills": "skills/",
        "mcpServers": "mcp.json",
    })
    emit_json(".cursor-plugin/marketplace.json", {
        "name": "gupshup",
        "owner": {"name": "Gupshup", "email": CFG["sales_email"]},
        "plugins": [{
            "name": "gupshup",
            "source": "plugins/gupshup-mcp",
            "description": cursor_desc,
            "version": CFG["version"],
            "author": {"name": "Gupshup"},
            "category": "Communication",
            "tags": ["whatsapp", "sms", "rcs", "messaging", "marketing"],
            "logo": "plugins/gupshup-mcp/assets/logo.svg",
        }],
    })


# ---------- README ----------
def readme_sections() -> dict[str, str]:
    t = CATALOG["totals"]
    apps_rows = ["| App | What your agent can do | OAuth scope | Tools | Context cost |", "|---|---|---|---|---|"]
    for app in CATALOG["apps"]:
        n = sum(1 for x in CATALOG["tools"] if x["app"] == app["key"] and not x["app_only"])
        apps_rows.append(
            f"| [{app['label']}](docs/reference/{app['key']}.md) | {app['summary']} | "
            f"{' '.join(f'`{s}`' for s in app['scopes'])} | {n} | ~{round(app['approx_tool_tokens'] / 100) / 10}k tokens |")
    tools_blocks = []
    for app in CATALOG["apps"]:
        tools_blocks.append(f"<details><summary><b>{app['label']}</b></summary>\n\n| Tool | What it does | Action |\n|---|---|---|")
        tools_blocks += [
            f"| [`{x['name']}`](docs/reference/{app['key']}.md#{x['name']}) | {md_escape(x['summary'])} | {RISK[x['risk']]} |"
            for x in CATALOG["tools"] if x["app"] == app["key"] and not x["app_only"]]
        tools_blocks.append("\n</details>\n")
    return {
        "endpoint": f"```\n{URL}\n```" + (
            f"\n\n> Already using `{CFG['mcp_url_legacy']}`? It stays supported permanently." if not CFG["use_legacy_as_primary"] else ""),
        "badges": install_buttons(),
        "claude-code": f"```bash\nclaude mcp add --transport http --scope user {NAME} {URL}\n```",
        "json": f"```json\n{json.dumps({'mcpServers': {NAME: {'type': 'http', 'url': URL}}}, indent=2)}\n```",
        "apps": "\n".join(apps_rows),
        "totals": (f"**{t['model_callable_tools']} tools** your agent can call, **{t['prompts']} prompts** and "
                   f"**{t['resources']} interactive review panels**, generated from the server code "
                   f"(catalog `{CATALOG.get('source_commit') or 'n/a'}`, {CATALOG['generated_at'][:10]})."),
        "tools": "\n".join(tools_blocks),
        "self-serve": (f"```bash\nclaude mcp add --transport http --scope user {SS['server_name']} {SS['mcp_url']} "
                       f"--header \"{SS['auth_header']}: ${SS['env_var']}\"\n```"),
    }


def render_readme() -> None:
    path = ROOT / "README.md"
    text = path.read_text()
    for key, body in readme_sections().items():
        pattern = re.compile(rf"(<!-- BEGIN:{re.escape(key)} -->\n)(?:.*?\n)?(<!-- END:{re.escape(key)} -->)", re.S)
        if not pattern.search(text):
            sys.exit(f"README.md is missing the <!-- BEGIN:{key} --> / <!-- END:{key} --> markers")
        text = pattern.sub(lambda m: m.group(1) + body + "\n" + m.group(2), text)
    outputs[path] = text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    render_reference()
    render_prompts()
    render_clients()
    render_self_serve()
    render_manifests()
    render_readme()

    stale = []
    for path, content in outputs.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path.relative_to(ROOT))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    if args.check and stale:
        print("out of date (run python3 scripts/render_docs.py):", *stale, sep="\n  ")
        sys.exit(1)
    print(f"rendered {len(outputs)} files ({len(stale)} changed); server URL {URL}")


if __name__ == "__main__":
    main()
